name: ollama_chat
services:
  app:
    build:
      context: .
      args:
        - NODE_VERSION=${NODE_VERSION}
    image: rpontual/ollama_chat_app:latest
    ports:
      - ${EXTERNAL_PORT}:3000
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_OLLAMA_URL=${NEXT_PUBLIC_OLLAMA_URL}
